#ifndef PROTO_FREETYPE_H
#define PROTO_FREETYPE_H

/*
** This file was machine generated by idltool.py 54.8.
** Do not edit.
**
** Prototype/inline/pragma header file combo.
*/

#include <freetype/freetype.h>
#include <freetype/freetype.h>
#include <freetype/ftbdf.h>
#include <freetype/ftcache.h>
#include <freetype/ftcolor.h>
#include <freetype/ftgxval.h>
#include <freetype/ftlcdfil.h>
#include <freetype/ftlist.h>
#include <freetype/ftlogging.h>
#include <freetype/ftmm.h>
#include <freetype/ftmodapi.h>
#include <freetype/ftoutln.h>
#include <freetype/ftsnames.h>
#include <freetype/ftstroke.h>
#include <freetype/fttrigon.h>
#include <freetype/ftwinfnt.h>
#include <freetype/t1tables.h>
#include <freetype/tttables.h>

/****************************************************************************/

#ifndef __NOLIBBASE__
 #ifndef __USE_BASETYPE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::Library * FreetypeBase;
  #else
   extern struct Library * FreetypeBase;
  #endif
 #else
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::FreetypeLibrary * FreetypeBase;
  #else
   extern struct FreetypeLibrary * FreetypeBase;
  #endif
 #endif /* __USE_BASETYPE__ */
#endif /* __NOLIBBASE__ */

/****************************************************************************/

#ifdef __amigaos4__
 #include <interfaces/freetype.h>
 #ifdef __USE_INLINE__
  #include <inline4/freetype.h>
 #endif /* __USE_INLINE__ */
 #ifndef CLIB_FREETYPE_PROTOS_H
  #define CLIB_FREETYPE_PROTOS_H 1
 #endif /* CLIB_FREETYPE_PROTOS_H */
 #ifndef __NOGLOBALIFACE__
  #if defined(__cplusplus) && defined(__USE_AMIGAOS_NAMESPACE__)
   extern struct AmigaOS::FreetypeIFace * IFreetype;
  #else
   extern struct FreetypeIFace * IFreetype;
  #endif
 #endif /* __NOGLOBALIFACE__ */
#else /* __amigaos4__ */
 #ifndef CLIB_FREETYPE_PROTOS_H
  #include <clib/freetype_protos.h>
 #endif /* CLIB_FREETYPE_PROTOS_H */
 #if defined(__GNUC__)
  #ifndef __PPC__
   #include <inline/freetype.h>
  #else /* __PPC__ */
   #include <ppcinline/freetype.h>
  #endif /* __PPC__ */
 #elif defined(__VBCC__)
  #ifndef __PPC__
   #include <inline/freetype_protos.h>
  #endif /* __PPC__ */
 #else /* __GNUC__ */
  #include <pragmas/freetype_pragmas.h>
 #endif /* __GNUC__ */
#endif /* __amigaos4__ */

/****************************************************************************/

#endif /* PROTO_FREETYPE_H */
